/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.xbase.testlanguages.bug462047.ui.AbstractBug462047LangUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Bug462047LangUiModule extends AbstractBug462047LangUiModule {
  public Bug462047LangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
