/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Bug462047LangUiModule extends AbstractBug462047LangUiModule {
}
