/**
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.scoping;

import org.eclipse.xtext.ui.tests.changeserializer.scoping.AbstractChangeSerializerScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ChangeSerializerScopeProvider extends AbstractChangeSerializerScopeProvider {
}
