/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.ide


/**
 * Use this class to register ide components.
 */
class ChangeSerializerIdeModule extends AbstractChangeSerializerIdeModule {
}
