/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.ide

import com.google.inject.Guice
import org.eclipse.xtext.ui.tests.changeserializer.ChangeSerializerRuntimeModule
import org.eclipse.xtext.ui.tests.changeserializer.ChangeSerializerStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ChangeSerializerIdeSetup extends ChangeSerializerStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ChangeSerializerRuntimeModule, new ChangeSerializerIdeModule))
	}
	
}
