/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ContentAssistFragmentTestLangUiModule extends AbstractContentAssistFragmentTestLangUiModule {
}
