/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ContentAssistFragmentTestLangDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
