grammar org.eclipse.xtext.ui.tests.changeserializer.ChangeSerializer with org.eclipse.xtext.common.Terminals

generate changeSerializer "http://www.eclipse.org/xtext/ui/tests/changeserializer/ChangeSerializer"

PackageDeclaration:
	'package' name=QualifiedName
	imports+=Import*
	contents+=Element*;

Import:
	'import' element=[Element|QualifiedName];
	
Element:
	'element' name=ID '{'
		(contents+=Element | 'ref' ref+=[Element|QualifiedName])*
	'}';
	
QualifiedName:
	ID ('.' ID)*;