/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ChangeSerializerStandaloneSetup extends ChangeSerializerStandaloneSetupGenerated {

	def static void doSetup() {
		new ChangeSerializerStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
