/**
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.tests.changeserializer.ChangeSerializerRuntimeModule;
import org.eclipse.xtext.ui.tests.changeserializer.ChangeSerializerStandaloneSetup;
import org.eclipse.xtext.ui.tests.changeserializer.ide.ChangeSerializerIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ChangeSerializerIdeSetup extends ChangeSerializerStandaloneSetup {
  @Override
  public Injector createInjector() {
    ChangeSerializerRuntimeModule _changeSerializerRuntimeModule = new ChangeSerializerRuntimeModule();
    ChangeSerializerIdeModule _changeSerializerIdeModule = new ChangeSerializerIdeModule();
    return Guice.createInjector(Modules2.mixin(_changeSerializerRuntimeModule, _changeSerializerIdeModule));
  }
}
