/**
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.ide;

import org.eclipse.xtext.ui.tests.changeserializer.ide.AbstractChangeSerializerIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ChangeSerializerIdeModule extends AbstractChangeSerializerIdeModule {
}
