/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.eclipse.xtext.ui.tests.changeserializer.ui.internal.ChangeserializerActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChangeSerializerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ChangeserializerActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ChangeserializerActivator.getInstance().getInjector(ChangeserializerActivator.ORG_ECLIPSE_XTEXT_UI_TESTS_CHANGESERIALIZER_CHANGESERIALIZER);
	}
	
}
