/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.xbase.testlanguages.ui.AbstractXImportSectionTestLangUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XImportSectionTestLangUiModule extends AbstractXImportSectionTestLangUiModule {
  public XImportSectionTestLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
