/**
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer;

import org.eclipse.xtext.ui.tests.changeserializer.ChangeSerializerStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ChangeSerializerStandaloneSetup extends ChangeSerializerStandaloneSetupGenerated {
  public static void doSetup() {
    new ChangeSerializerStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
