/**
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.ui.tests.changeserializer.AbstractChangeSerializerRuntimeModule;
import org.eclipse.xtext.ui.tests.changeserializer.scoping.ChangeSerializerImportScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ChangeSerializerRuntimeModule extends AbstractChangeSerializerRuntimeModule {
  @Override
  public void configureIScopeProviderDelegate(final Binder binder) {
    binder.<IScopeProvider>bind(IScopeProvider.class).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(ChangeSerializerImportScopeProvider.class);
  }
}
