rm tests/org/eclipse/xtext/common/types/access/ClasspathTypeProviderFactoryTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderPerformanceTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/BinaryClassFinderTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/BinaryClassMirrorTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/BinarySignaturesTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/ClassFinderTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/ClassMirrorTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/ClassNameUtilTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/ClasspathTypeProviderTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/ClasspathTypeProviderWithoutASMTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/ClassURIHelperTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/JarClasspathTypeProviderTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/PrimitiveMirrorTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/PrimitivesTest.java
rm tests/org/eclipse/xtext/common/types/access/impl/PrimitiveTypeFactoryTest.java
rm tests/org/eclipse/xtext/common/types/access/reflect/JarReflectionTypeProviderTest.java
rm tests/org/eclipse/xtext/common/types/access/reflect/ReflectionTypeProviderTest.java
rm tests/org/eclipse/xtext/common/types/access/reflect/ReflectURIHelperTest.java
rm tests/org/eclipse/xtext/common/types/access/TypeResourceTest.java
rm tests/org/eclipse/xtext/common/types/access/xtext/AbstractConstructorScopeTest.java
rm tests/org/eclipse/xtext/common/types/access/xtext/AbstractTypeScopeTest.java
rm tests/org/eclipse/xtext/common/types/access/xtext/ClasspathBasedConstructorScopeTest.java
rm tests/org/eclipse/xtext/common/types/access/xtext/ClasspathBasedTypeScopeTest.java
rm tests/org/eclipse/xtext/common/types/JvmArrayTypeTest.java
rm tests/org/eclipse/xtext/common/types/JvmBooleanAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmByteAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmCharAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmComponentTypeTest.java
rm tests/org/eclipse/xtext/common/types/JvmConstructorTest.java
rm tests/org/eclipse/xtext/common/types/JvmDeclaredTypeTest.java
rm tests/org/eclipse/xtext/common/types/JvmDoubleAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmExecutableTest.java
rm tests/org/eclipse/xtext/common/types/JvmFeatureTest.java
rm tests/org/eclipse/xtext/common/types/JvmFieldTest.java
rm tests/org/eclipse/xtext/common/types/JvmFloatAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmFormalParameterTest.java
rm tests/org/eclipse/xtext/common/types/JvmGenericTypeTest.java
rm tests/org/eclipse/xtext/common/types/JvmInnerTypeReferenceTest.java
rm tests/org/eclipse/xtext/common/types/JvmIntAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmLongAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmLowerBoundTest.java
rm tests/org/eclipse/xtext/common/types/JvmParameterizedTypeReferenceTest.java
rm tests/org/eclipse/xtext/common/types/JvmPrimitiveTypeTest.java
rm tests/org/eclipse/xtext/common/types/JvmShortAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmStringAnnotationValueTest.java
rm tests/org/eclipse/xtext/common/types/JvmTypeParameterTest.java
rm tests/org/eclipse/xtext/common/types/JvmUpperBoundTest.java
rm tests/org/eclipse/xtext/common/types/JvmVoidTest.java
rm tests/org/eclipse/xtext/common/types/JvmWildcardTypeReferenceTest.java
rm tests/org/eclipse/xtext/common/types/util/DeprecationUtilTest.java
rm tests/org/eclipse/xtext/common/types/util/JavaReflectAccessTest.java
rm tests/org/eclipse/xtext/common/types/util/JvmTypeReferencesTest.java
