/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.ui.tests.changeserializer.parser.antlr.internal.InternalChangeSerializerParser;
import org.eclipse.xtext.ui.tests.changeserializer.services.ChangeSerializerGrammarAccess;

public class ChangeSerializerParser extends AbstractAntlrParser {

	@Inject
	private ChangeSerializerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalChangeSerializerParser createParser(XtextTokenStream stream) {
		return new InternalChangeSerializerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PackageDeclaration";
	}

	public ChangeSerializerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ChangeSerializerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
