/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ChangeSerializerAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/xtext/ui/tests/changeserializer/parser/antlr/internal/InternalChangeSerializer.tokens");
	}
}
