/*
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.scoping

import com.google.inject.Inject
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.IGlobalScopeProvider
import org.eclipse.xtext.ui.tests.changeserializer.changeSerializer.ChangeSerializerPackage

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ChangeSerializerScopeProvider extends AbstractChangeSerializerScopeProvider {

	@Inject IGlobalScopeProvider global

	override getScope(EObject context, EReference reference) {
		if (reference === ChangeSerializerPackage.Literals.IMPORT__ELEMENT) {
			return global.getScope(context.eResource, reference, null)
		}
		return super.getScope(context, reference)
	}

}
