/**
 * generated by Xtext unspecified
 */
package org.eclipse.xtext.ui.tests.changeserializer.validation;

import org.eclipse.xtext.ui.tests.changeserializer.validation.AbstractChangeSerializerValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ChangeSerializerValidator extends AbstractChangeSerializerValidator {
}
